org.gradle.jvmargs=-Xmx3G
# Loom ist nicht mit dem Configuration-Cache kompatibel.
org.gradle.configuration-cache=false
# Architectury-Loom: Zielplattform Forge.
loom.platform=forge

# Mod
mod_version=0.1.0
maven_group=dev.theredstonee.trsclient


# Minecraft / Forge 1.8.9 (letzte empfohlene Forge-Version für 1.8.9)
minecraft_version=1.8.9
forge_version=1.8.9-11.15.1.2318-1.8.9
mcp_mappings=de.oceanlabs.mcp:mcp_stable:22-1.8.9

# Bibliotheken
junit_version=5.12.2
# Gson-Version, die Minecraft 1.8.9 selbst mitliefert (nur für Tests).
gson_version=2.2.4
