import { emptyGrid, hexToPx, type PixelGrid } from './iconEditor'

/*
 * Fertige TRS-Symbole für den Symbol-Editor: eigene Pixel-Art (16 × 16, GPL-3.0 wie der Launcher),
 * als Text gezeichnet – ein Zeichen je Pixel, `.` = durchsichtig. Farben siehe `TRS_ICON_COLORS`.
 */

export const TRS_ICON_COLORS: Record<string, string> = {
  k: '#1b1420', // Umriss
  x: '#4a4652',
  s: '#8b8b95',
  S: '#c7c7cf',
  w: '#ffffff',
  r: '#d42a1f', // Redstone
  R: '#ff5a45',
  d: '#7a1410',
  l: '#ff9c8a',
  g: '#f2c230', // Gold
  G: '#ffe27a',
  o: '#e8862a',
  b: '#3c7ee8',
  B: '#8fd3ff',
  n: '#23408f',
  e: '#4caf3a',
  E: '#8be06a',
  f: '#24642a',
  p: '#8e4fd6',
  P: '#c39af5',
  y: '#8a5a2b', // Holz
  Y: '#c08a4f',
  c: '#45e0d0',
  C: '#b5fff5',
  a: '#e9d8a6', // Papier
  m: '#ff6fb5',
}

const E = '................'

/** Inhalt mittig in 16 Zeilen setzen (`top` = Leerzeilen davor). */
function rows(top: number, lines: string[], shift = 0): string[] {
  const shifted = lines.map((l) => (shift > 0 ? '.'.repeat(shift) + l.slice(0, 16 - shift) : shift < 0 ? l.slice(-shift) + '.'.repeat(-shift) : l))
  const out = [...Array<string>(top).fill(E), ...shifted]
  while (out.length < 16) out.push(E)
  return out
}

export const TRS_ICONS = {
  rocket: rows(0, [
    '.......kk.......',
    '......kRrk......',
    '.....kRrrdk.....',
    '.....kwwSSk.....',
    '.....kwBbSk.....',
    '.....kBbbSk.....',
    '.....kwbbSk.....',
    '.....kwwSSk.....',
    '.....kwwSSk.....',
    '....kkwwSSkk....',
    '...kRkwwSSkdk...',
    '...kRkrrrdkdk...',
    '...kkkkkkkkkk...',
    '......kogok.....',
    '......kgGgk.....',
    '.......kok......',
  ]),
  castle: rows(1, [
    '.k.k.k....k.k.k.',
    '.kkkkk....kkkkk.',
    '.kSSSk....kSSSk.',
    '.kSxSk....kSxSk.',
    '.kSxSkk.k.kSxSk.',
    '.kSSSkkkkkkSSSk.',
    '.kSSSSsSSsSSSSk.',
    '.kSsSSSSSSSSsSk.',
    '.kSSSSSkkSSSSSk.',
    '.kSSsSkyykSsSSk.',
    '.kSSSSkyYkSSSSk.',
    '.kSsSSkyYkSSsSk.',
    '.kSSSSkyykSSSSk.',
    '.kkkkkkkkkkkkkk.',
  ]),
  redstone: rows(0, [
    '.......dr.......',
    '.......rR.......',
    '......drRd......',
    '.......Rr.......',
    '.......rd.......',
    '......rRRr......',
    '.....rRllRr.....',
    'drRrRRllllRRrRrd',
    'drrRrRllllRrRrrd',
    '.....rRllRr.....',
    '......rRRr......',
    '.......rd.......',
    '.......Rr.......',
    '......drRd......',
    '.......rR.......',
    '.......dr.......',
  ]),
  comparator: rows(1, [
    '.kkkkkkkkkkkkkk.',
    '.kSSSSSllSSSSSk.',
    '.kSsSSSRRSSSsSk.',
    '.kSSSSSddSSSSSk.',
    '.kSSSSSSSSSSSSk.',
    '.kSsSSSrrSSSsSk.',
    '.kSSSSSrrSSSSSk.',
    '.kSrrrrrrrrrrSk.',
    '.kSrSSSSSSSSrSk.',
    '.kSllSSSSSSllSk.',
    '.kSRRSSSSSSRRSk.',
    '.kSddSSsSSSddSk.',
    '.kSSSSSSSSSSSSk.',
    '.kkkkkkkkkkkkkk.',
  ]),
  repeater: rows(1, [
    '.kkkkkkkkkkkkkk.',
    '.kSSSSSllSSSSSk.',
    '.kSsSSSRRSSSsSk.',
    '.kSSSSSddSSSSSk.',
    '.kSSSSSrrSSSSSk.',
    '.kSSsSSrrSSSSSk.',
    '.kSSSSSllSSsSSk.',
    '.kSSSSSRRSSSSSk.',
    '.kSsSSSddSSSSSk.',
    '.kSSSSSrrSSSsSk.',
    '.kSSSSSrrSSSSSk.',
    '.kSSsSSrrSSSSSk.',
    '.kSSSSSSSSSSSSk.',
    '.kkkkkkkkkkkkkk.',
  ]),
  torch: rows(1, [
    '......l..l......',
    '.......ll.......',
    '......lRRl......',
    '......RRrR......',
    '......dRrd......',
    '.......dd.......',
    '.......Yy.......',
    '.......Yy.......',
    '.......Yy.......',
    '.......Yy.......',
    '.......Yy.......',
    '.......Yy.......',
    '.......Yy.......',
    '.......yy.......',
  ]),
  lamp: rows(1, [
    '.kkkkkkkkkkkkkk.',
    '.kyyyyyyyyyyyyk.',
    '.kyGGGGyyGGGGyk.',
    '.kyGwGgyyGgwGyk.',
    '.kyGGgGyyGgGGyk.',
    '.kyGgGGyyGGgGyk.',
    '.kyyyyyyyyyyyyk.',
    '.kyyyyyyyyyyyyk.',
    '.kyGGgGyyGgGGyk.',
    '.kyGwGGyyGGwGyk.',
    '.kyGgGGyyGGgGyk.',
    '.kyGGGgyyGGGGyk.',
    '.kyyyyyyyyyyyyk.',
    '.kkkkkkkkkkkkkk.',
  ]),
  sun: rows(0, [
    '.......gg.......',
    '.......gg.......',
    '..g....GG....g..',
    '...g..gggg..g...',
    '.....gGGGGg.....',
    '....gGwwGGGg....',
    '....gGwGGGGg....',
    'ggGgGGGGGGGGgGgg',
    'ggGgGGGGGGGogGgg',
    '....gGGGGGog....',
    '....gGGGGoog....',
    '.....goooog.....',
    '...g..gggg..g...',
    '..g....GG....g..',
    '.......gg.......',
    '.......gg.......',
  ]),
  sword: rows(1, [
    '..............w.',
    '............swS.',
    '...........swS..',
    '..........swS...',
    '.........swS....',
    '........swS.....',
    '.......swS......',
    '...g..swS.......',
    '....gswS........',
    '.....G..........',
    '....y.g.........',
    '...y...g........',
    '..G.............',
  ]),
  pickaxe: rows(1, [
    '...cccccc.......',
    '..cCCCCCCcc.....',
    '.cc.....CCCc....',
    '.c......YyCCc...',
    '.......Yy..cCc..',
    '......Yy....cCc.',
    '.....Yy.....cCc.',
    '....Yy......cCc.',
    '...Yy.......cCc.',
    '..Yy.........cc.',
    '.Yy..........c..',
    'Yy..............',
  ]),
  axe: rows(1, [
    '...........Yy...',
    '......sssSsYy...',
    '.....sSSSSsYy...',
    '....sSSSSSsYy...',
    '....sSwSSSsYy...',
    '....sSSSSSsYy...',
    '.....sSSSSsYy...',
    '......sssSsYy...',
    '...........Yy...',
    '...........Yy...',
    '...........Yy...',
    '...........Yy...',
    '...........Yy...',
    '...........yy...',
  ], -2),
  bow: rows(1, [
    '.........yS.....',
    '.......yY.S.....',
    '......yY..S.....',
    '.....yY...S.....',
    '.....yY...S.....',
    '....yY....S.....',
    '....yY....S.....',
    '....yY....S.....',
    '....yY....S.....',
    '.....yY...S.....',
    '.....yY...S.....',
    '......yY..S.....',
    '.......yY.S.....',
    '.........yS.....',
  ]),
  shield: rows(1, [
    '..kkkkkkkkkkkk..',
    '..krrrrggrrrrk..',
    '..krRrrggrrRrk..',
    '..krrrrggrrrrk..',
    '..kggggggggggk..',
    '..kggggggggggk..',
    '..krrrrggrrrrk..',
    '..krrrrggrrrrk..',
    '...krrrggrrrk...',
    '...krrrggrrrk...',
    '....krrggrrk....',
    '.....krggrk.....',
    '......kggk......',
    '.......kk.......',
  ]),
  map: rows(1, [
    '.kkkkkkkkkkkkkk.',
    '.kaaaaaaaaaaaak.',
    '.kaEEaaaaararak.',
    '.kaEEEaaaaaraak.',
    '.kaaEaaaaararak.',
    '.kaaaaaaaaaaaak.',
    '.kaaaaaaaraaaak.',
    '.kaaaaaaraabbak.',
    '.kaaaaaraaabbak.',
    '.kaaaraaaaabbak.',
    '.kaaaaaaaaaaaak.',
    '.karaaaaaaeEaak.',
    '.kaaaaaaaaeeaak.',
    '.kkkkkkkkkkkkkk.',
  ]),
  flask: rows(1, [
    '......kkkk......',
    '......kyyk......',
    '......kSSk......',
    '......kwSk......',
    '.....kSwSSk.....',
    '....kSwSSSSk....',
    '...kSPPPPPPSk...',
    '...kPPwPPPPPk...',
    '..kPpPPPwPPPPk..',
    '..kpPPPPPPPpPk..',
    '..kppPPPPPppPk..',
    '..kpppppppppPk..',
    '...kpppppppPk...',
    '....kkkkkkkk....',
  ]),
  heart: rows(2, [
    '..kkkk....kkkk..',
    '.kRRrrk..kRrrrk.',
    'kRwRrrrkkrrrrrdk',
    'kRRrrrrrrrrrrrdk',
    'krrrrrrrrrrrrrdk',
    'krrrrrrrrrrrrddk',
    '.krrrrrrrrrrrdk.',
    '..krrrrrrrrrdk..',
    '...krrrrrrrdk...',
    '....krrrrrdk....',
    '.....krrrdk.....',
    '......krdk......',
    '.......kk.......',
  ]),
  crown: rows(3, [
    '.k.....kk.....k.',
    'kGk...kGGk...kGk',
    'kgk...kggk...kgk',
    'kggk..kggk..kggk',
    'kgggkkggggkkgggk',
    'kggggggggggggggk',
    'kggrrggbbggrrggk',
    'kggrrggbbggrrggk',
    'kggggggggggggggk',
    'kGGGGGGGGGGGGGGk',
    'kkkkkkkkkkkkkkkk',
  ]),
  star: rows(1, [
    '.......kk.......',
    '......kGgk......',
    '......kGgk......',
    '.....kGggok.....',
    'kkkkkkGgggokkkkk',
    'kGGGGGGggggggook',
    '.kGGGggggggggok.',
    '..kGgggggggggk..',
    '...kgggggggok...',
    '...kgggggggok...',
    '..kggggkkgggok..',
    '..kgggk..kgggk..',
    '.kgggk....kgook.',
    '.kggk......kgok.',
    '.kkk........kkk.',
  ]),
  lightning: rows(1, [
    '.........kkkk...',
    '........kGGgk...',
    '.......kGggk....',
    '......kGggk.....',
    '.....kGggk......',
    '....kGgggkkkk...',
    '...kGgggggggk...',
    '...kkkkkGggk....',
    '.......kGgk.....',
    '......kGgk......',
    '.....kGgk.......',
    '....kGgk........',
    '...kGgk.........',
    '...kgk..........',
    '...kk...........',
  ]),
  tree: rows(1, [
    '......kkkk......',
    '....kkEEEEkk....',
    '...kEEeEEEeEk...',
    '..kEeeEEeeEEek..',
    '..keEEeeEEeEek..',
    '.kEeeEEEeeeEEek.',
    '.keEEeeeEEeeeEk.',
    '.kfeeEEeeeEeeek.',
    '..kffeeeeeeffk..',
    '...kkffYyffkk...',
    '......kYyk......',
    '......kYyk......',
    '......kYyk......',
    '.....kkYykk.....',
  ]),
  house: rows(1, [
    '.......kk.......',
    '......krrk......',
    '.....krRRrk.....',
    '....krRrrRrk....',
    '...krRrrrrRrk...',
    '..krRrrrrrrRrk..',
    '.kkkkkkkkkkkkkk.',
    '..kYyYYYYYYyYk..',
    '..kYkkkYkkkkYk..',
    '..kYkBkYkyykYk..',
    '..kYkkkYkyykYk..',
    '..kYYYYYkygkYk..',
    '..kYYYYYkyykYk..',
    '..kkkkkkkkkkkk..',
  ]),
  gear: rows(1, [
    '......kkkk......',
    '..kk..kSSk..kk..',
    '.kSSkkSSSSkkSSk.',
    '.kSSSSSSSSSSSSk.',
    '..kSSSSkkSSSSk..',
    'kkkSSSk..kSSSkkk',
    'kSSSSk....kSSssk',
    'kSSSSk....kSssSk',
    'kkkSSSk..kSSSkkk',
    '..kSSSSkkSSSsk..',
    '.kSSSSSSSSSssSk.',
    '.kSSkkSSSskksSk.',
    '..kk..kSsk..kk..',
    '......kkkk......',
  ]),
  controller: rows(4, [
    '..kkkkkkkkkkkk..',
    '.kxxxxxxxxxxxxk.',
    'kxxSxxxxxxxxrxxk',
    'kxSSSxxxxxxrxbxk',
    'kxxSxxxkkxxxgxxk',
    'kxxxxxxxxxxxxxxk',
    'kxxxxkkkkkkxxxxk',
    'kxxxk......kxxxk',
    '.kkk........kkk.',
  ]),
  globe: rows(1, [
    '.....kkkkkk.....',
    '...kkbbeebbkk...',
    '..kbbbeEebbbbk..',
    '.kbbbeeEeebbbbk.',
    '.kbbbbeeebbbeek.',
    'kbbbbbbebbbbeEek',
    'kbBbbbbbbbbeeEek',
    'kbbBbbbbbbbbeeek',
    'kbbbbeebbbbbbeek',
    '.kbbbeEeebbbbbk.',
    '.kbbbbeebbbbbbk.',
    '..kbbbbbbbbbbk..',
    '...kkbbbbbbkk...',
    '.....kkkkkk.....',
  ]),
  book: rows(1, [
    '..kkkkkkkkkkk...',
    '..krrrrrrrrrSk..',
    '..krRRRRRRrrSk..',
    '..krrgggggrrSk..',
    '..krrrrrrrrrSk..',
    '..krrgggrrrrSk..',
    '..krrrrrrrrrSk..',
    '..krrrrrrrrrSk..',
    '..krrrrrrrrrSk..',
    '..krrrrrrrrrSk..',
    '..krrrrrrrrrSk..',
    '..kdkkkkkkkkSk..',
    '..kdwwwwwwwwwk..',
    '...kkkkkkkkkkk..',
  ]),
  gem: rows(3, [
    '....kkkkkkkk....',
    '...kCwCcCCcck...',
    '..kCCCcCCCccck..',
    '.kcccccccccccnk.',
    '..kcCCcccccnnk..',
    '...kcCcccccnk...',
    '....kcCcccnk....',
    '.....kcccnk.....',
    '......kcnk......',
    '.......kk.......',
  ]),
  cube: rows(1, [
    '.......kk.......',
    '.....kkEEkk.....',
    '...kkEEEEEEkk...',
    '.kkEEEEEEEEEEkk.',
    '.kyeeEEEEEEeeYk.',
    '.kyyyeeEEeeYYYk.',
    '.kyyyyyeeYYYYYk.',
    '.kyyxyyyYYYyYYk.',
    '.kyyyyyyYYYYYYk.',
    '.kyxyyyyYYYYyYk.',
    '.kkyyyyyYYYYYkk.',
    '...kkyyyYYYkk...',
    '.....kkyYkk.....',
    '.......kk.......',
  ]),
  chest: rows(2, [
    '.kkkkkkkkkkkkkk.',
    '.kYYYYYYYYYYYYk.',
    '.kYyyyyyyyyyyYk.',
    '.kYyyyyyyyyyyYk.',
    '.kkkkkkSSkkkkkk.',
    '.kYyyyySSyyyyYk.',
    '.kYyyyykkyyyyYk.',
    '.kYyyyyyyyyyyYk.',
    '.kYyyyyyyyyyyYk.',
    '.kYyyyyyyyyyyYk.',
    '.kYYYYYYYYYYYYk.',
    '.kkkkkkkkkkkkkk.',
  ]),
  mushroom: rows(1, [
    '.....kkkkkk.....',
    '...kkrrwwrrkk...',
    '..krrrrwwrrrrk..',
    '.krwwrrrrrrwwrk.',
    '.krwwrrrrrrwwrk.',
    'krrrrrrwwrrrrrdk',
    'kdrrrrrwwrrrrddk',
    '.kkkkkkkkkkkkkk.',
    '.....kSwwSk.....',
    '.....kSwSSk.....',
    '.....kSSSSk.....',
    '....kSSSSSSk....',
    '....kkkkkkkk....',
  ]),
  flame: rows(1, [
    '.......k........',
    '......kok.......',
    '......kook......',
    '.....koook..k...',
    '....koogok.kok..',
    '...kooggokkoook.',
    '..koogGGgoooook.',
    '..kogGwGGggoook.',
    '.kooGwwGGgggook.',
    '.korGwwwGGgggok.',
    '.korgGwwGGggrok.',
    '.krrogGGGggorrk.',
    '..krroggggorrk..',
    '...kdrrooorrdk..',
    '....kkdddddkk...',
  ]),
  snowflake: rows(0, [
    '.......C........',
    '.B...B.C.B...B..',
    '..B....C....B...',
    '...B...C...B....',
    '....B..C..B.....',
    '.B...B.C.B...B..',
    '......BCB.......',
    'CCCCCCCwCCCCCCC.',
    '......BCB.......',
    '.B...B.C.B...B..',
    '....B..C..B.....',
    '...B...C...B....',
    '..B....C....B...',
    '.B...B.C.B...B..',
    '.......C........',
  ], 1),
  moon: rows(1, [
    '.....kkkk.......',
    '...kkGGk........',
    '..kGGgk.....w...',
    '.kGGgk..........',
    '.kGgk...........',
    'kGGgk...........',
    'kGggk...........',
    'kGggk...........',
    'kGGggk..........',
    '.kGGggk.....kk..',
    '.kGGgggkkkkkGk..',
    '..kGGGggggGGk...',
    '...kkGGGGGkk....',
    '.....kkkkk......',
  ], 2),
  cloud: rows(3, [
    '......kkkk......',
    '.....kwwwwk.....',
    '..kkkwwwwwwk....',
    '.kwwwwwwwwwwkk..',
    '.kwwwwwwwwwwwwk.',
    'kwwwwwwwwwwwwwwk',
    'kSwwwwwwwwwwwwSk',
    '.kSSSSSSSSSSSSk.',
    '..kkkkkkkkkkkk..',
  ]),
  note: rows(2, [
    '......ppppppp...',
    '......pPPPPPp...',
    '......p.....p...',
    '......p.....p...',
    '......p.....p...',
    '......p.....p...',
    '......p.....p...',
    '......p.....p...',
    '...pppp..pppp...',
    '..pPPpp.pPPpp...',
    '..ppppp.ppppp...',
    '...ppp...ppp....',
  ], 1),
  flag: rows(1, [
    '..kk............',
    '..kSkkkkkkkkk...',
    '..kSkrrRRrrrrk..',
    '..kSkrRRrrrrrrk.',
    '..kSkrrrrrrrrrk.',
    '..kSkdrrrrrrrdk.',
    '..kSkkkdrrrrdk..',
    '..kSk..kkkkkk...',
    '..kSk...........',
    '..kSk...........',
    '..kSk...........',
    '..kSk...........',
    '.kkSkk..........',
    '.kkkkk..........',
  ], 1),
  trophy: rows(1, [
    '...kkkkkkkkkk...',
    '.kkkGGgggggokkk.',
    'kgkkGGgggggokkgk',
    'kg.kGggggggok.gk',
    '.kgkGggggggokgk.',
    '..kkkGggggokkk..',
    '....kGggggok....',
    '.....kGggok.....',
    '......kGgk......',
    '.......gg.......',
    '......kggk......',
    '....kkkkkkkk....',
    '....kyyyyyyk....',
    '....kkkkkkkk....',
  ]),
  key: rows(4, [
    '..kkkk..........',
    '.kGGggk.........',
    'kGgkkgok........',
    'kGk..kokkkkkkkk.',
    'kgk..kogggggggok',
    '.kgookkkkkkgkgk.',
    '..kkkk.....kkkk.',
  ]),
  compass: rows(1, [
    '.....kkkkkk.....',
    '...kkSSSSSSkk...',
    '..kSwwwrrwwwSk..',
    '.kSwwwwrrwwwwSk.',
    '.kSwwwrRRrwwwSk.',
    'kSwwwwrRRrwwwwSk',
    'kSwwwwwkkwwwwwSk',
    'kSwwwwxSSxwwwwSk',
    'kSwwwwxSSxwwwwSk',
    '.kSwwwxSSxwwwSk.',
    '.kSwwwwxxwwwwSk.',
    '..kSwwwxxwwwSk..',
    '...kkSSSSSSkk...',
    '.....kkkkkk.....',
  ]),
  wrench: rows(1, [
    '.........kk..kk.',
    '.........kSk.kSk',
    '.........kSkkkSk',
    '.........kSSSSSk',
    '........kSSSSSk.',
    '.......kSSkkkk..',
    '......kSSk......',
    '.....kSSk.......',
    '....kSSk........',
    '...kSSk.........',
    '..kSSk..........',
    '.kSSk...........',
    '.kSk............',
    '..k.............',
  ]),
  robot: rows(1, [
    '.......ll.......',
    '.......kk.......',
    '..kkkkkkkkkkkk..',
    '..kSSSSSSSSSSk..',
    '..kSkkkSSkkkSk..',
    '..kSkBkSSkBkSk..',
    '..kSkkkSSkkkSk..',
    '..kSSSSSSSSSSk..',
    '.kkSSrrrrrrSSkk.',
    '.kSkSSSSSSSSkSk.',
    '.kkkSSSSSSSSkkk.',
    '...kkkkkkkkkk...',
  ], 0),
} satisfies Record<string, string[]>

export type TrsIconId = keyof typeof TRS_ICONS

export const TRS_ICON_IDS = Object.keys(TRS_ICONS) as TrsIconId[]

/** Text-Zeichnung → Raster (unbekannte Zeichen = durchsichtig). */
export function trsIconGrid(id: string): PixelGrid | null {
  const art = (TRS_ICONS as Record<string, string[] | undefined>)[id]
  if (!art) return null
  const grid = emptyGrid(16)
  art.forEach((line, y) => {
    for (let x = 0; x < 16; x++) {
      const color = TRS_ICON_COLORS[line[x] ?? '.']
      if (color) grid.px[y * 16 + x] = hexToPx(color)
    }
  })
  return grid
}
